import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { coreFunc } from "@sangotaro/core/utils/functions";
import { Title } from "@sangotaro/core/components/Title/index";
// not working
// import { Title } from "@sangotaro/core/components/Title/index";

export const getServerSideProps: GetServerSideProps = async (context) => {
  console.log("This is getServerSideProps of @sangotaro/nextjs!");
  coreFunc();
  return { props: {} };
};

const Home: NextPage = () => {
  return (
    <div
      style={{
        minHeight: "100vh",
        padding: "0 0.5rem",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title />
    </div>
  );
};

export default Home;
